networks:
  cluster:
    driver: bridge

volumes:
  dbdata:  

services:
  postgres:
    image: postgres:alpine
    container_name: investQuest-DB
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - cluster
    volumes:
      - dbdata:/var/lib/postgresql/data
